---
- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-2171
    - profile-2171
    - user-2171
    - webserver-2171

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"